export const ADD_USER = 'ADD_USER';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const REMOVE_USER = 'REMOVE_USER';
export const ADD_REPOS = 'ADD_REPOS';
export const REPO_LOADING = 'REPO_LOADING';
export const CHANGE_NETWORK_CONNECTION_STATUS = 'CHANGE_NETWORK_CONNECTION_STATUS';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';